### ISSUE TITLE
Error about "moment is not a function"

### ISSUE THREAD

**Issue by Patlatus** [rapsacnz/DatePickerAura#1]
This page has an error. You might just need to refresh it.
Error during init [afterRender threw an error in 'markup://c:DatePickerApp' [afterRender threw an error in 'markup://aura:html' [afterRender threw an error in 'markup://aura:html' [afterRender threw an error in 'markup://c:DatePicker' [afterRender threw an error in 'markup://ltng:require' [Action failed: c$DatePicker$controller$doInit [moment is not a function]]]]]]]

![image](https://cloud.githubusercontent.com/assets/1489026/20926554/9116a706-bbc5-11e6-8b97-086940c1e5c9.png)

**Comment by rapsacnz** [comment]
The date picker app has a dependency to moment.js. Include it as a resource, and this issue should go away.

**Comment by rapsacnz** [comment]
Moment dependency has now been removed.
