### ISSUE TITLE
Code is not compiling

### ISSUE THREAD

**Issue by Patlatus** [rapsacnz/DatePickerAura#2]
Deployment Failed

Component Errors
 
API Name
Type
Line
Column
Error Message
DatePickerApp	Lightning Component Bundle	0	0	No COMPONENT named markup://c:SPEAR_DatePicker found : [markup://c:DatePickerApp]

**Comment by Patlatus** [comment]
Fixed locally on my environment using this patch

Index: DatePickerApp.app
===================================================================
--- DatePickerApp.app	(revision 9)
+++ DatePickerApp.app	(working copy)
@@ -8,7 +8,7 @@
   <div class="slds">
     <div class="slds-form">
 
-      <c:SPEAR_DatePicker label="Test Date" placeholder="Enter a Date" formatSpecifier="MM/dd/yyyy" />
+      <c:DatePicker label="Test Date" placeholder="Enter a Date" formatSpecifier="MM/dd/yyyy" />
 
     </div>
   </div>

**Comment by rapsacnz** [comment]
Thanks, have made the change to master - this was a namespace from one of my other projects.
