### ISSUE TITLE
When making a selection the previous day gets selected.

### ISSUE THREAD

**Issue by cotillardq** [rapsacnz/DatePickerAura#3]
When ever a user click on a date (say 12/29/2016), the calendar highlight (blue dot) 12/28/2016 instead.

**Comment by rapsacnz** [comment]
Thanks - I have a fix and will upload it along with quite a few other improvements) shortly after christmas.

**Comment by cotillardq** [comment]
Awesome. For now I have fixed it by changing
line ~ 98 var selectedDate = new Date(Date.UTC(year, month, dayOfMonth+1, 0, 0, 0));

**Comment by rapsacnz** [comment]
Hah, that's pretty similar to my fix

**Comment by rapsacnz** [comment]
My fix is now in place also. Closing.
