### ISSUE TITLE
Placeholder text incorrect and does not change with selection

### ISSUE THREAD

**Issue by BigBadChicago** [rapsacnz/DatePickerAura#6]
I've been trying to fix a bunch of things with the mess that Salesforce had made with localization with Summer 17.  Your datepicker component has been a lifesaver up until this week.  I think I have everything working, except that

- the placeholder text has been replaced with the format specified attribute.  I think this is done in the second line of the init function of the InputDateHelper.js file.  I've commented out that line, but it's still occurring.
- after user selects a date, the placeholder text does not display the date.  If you view the console, the logs display that the date is selected and in the correct format.  It's just that the placeholder text is still there, and still displaying the formatSpecified attribute.  

Any ideas where to get this changed or how to fix this?

**Comment by rapsacnz** [comment]
As it happens, I also had all those problems - including an `ui:inputDate` component that now always displays it's own, horrible, datepicker. I've fixed them all - including the formatted date placeholder text. Take a look at my updated readme on this component. You will need 3 new components - I think they are:


- `DateTimeLib` component, 
-   An update to the `Select` (for fixed year preselection)
-   A new `InputDate` component. 

It's working well for me and it was a nice relief to drop that dependency on `ui:inputDate` 

Let me know if the update fixes stuff for you. If you don't feel like completely replacing the `DatePicker`, you can just replace the `ui:inputDate` with the new `InputDate`

**Comment by rapsacnz** [comment]
Oh realised that I missed out the renderer file - very important, because it won't handle outside value updates without it!! - Add the render file for the InputDate and you'll find it all works.

**Comment by BigBadChicago** [comment]
That was exactly it.  Added that code, and it works perfectly again.  Thank you so much, Caspar!

**Comment by rapsacnz** [comment]
Awesome, glad that it's still working!
