### ISSUE TITLE
DatePicker calendar doesn't close 

### ISSUE THREAD

**Issue by ashutoshjha1409** [rapsacnz/DatePickerAura#8]
If we move focus from input field to year selected am no longer able to close the datepicker by clicking outside the calendar. 
Steps to reproduce:
1. change year
2. click anywhere outside the date picker.

Expected result: Date Picker should close
Actual result: DatePicker not closing

**Comment by rapsacnz** [comment]
Great. Fix it and submit a pull request thanks.

**Comment by rapsacnz** [comment]
That has been implemented as a clickoutside feature.
