### ISSUE TITLE
Uncaught Assertion Failed!: no client action by name c.handleClick : false

### ISSUE THREAD

**Issue by ghost** [rapsacnz/DatePickerAura#9]
I get this error when i click on and date 
Uncaught Assertion Failed!: no client action by name c.handleClick : false

**Comment by ghost** [comment]
cellCmp.addHandler("dateCellClick", component, "c.handleClick"); in the DatePickerController it cant read/access "c.handleClick" in the controller on click

**Comment by rapsacnz** [comment]
Change line 8 in the controller
```cellCmp.addHandler("dateCellClick", component, "c.handleClick");```
To:
```cellCmp.addEventHandler("dateCellClick", component.getReference("c.handleClick"));```
